package com.admin_management.model.bo;

public enum DepartmentType {
    ADMINISTRATIVE_COUNCIL, FINANCIAL_ACCOUNTANT, ADMINISTRATIVE_STAFF, QUALITY_AND_ASSET_MANAGEMENT,
    BUSINESS, TECHNICAL_MANAGEMENT, INFORMATION_TECHNOLOGY, WAREHOUSE, PETROL_STATIONS, CARRIAGE
}
